import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";
import ClientWrapper from "@/components/ClientWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    
      <ClerkProvider>
      
      <html lang="en">
      <body>
      <ClientWrapper/>
      <Header/>
      <div className="flex min-h-screen">
      <Sidebar/>
      <div className="flex-1 p-4 bg-gray-200 overflow-y-auto scrollbar-hide">{children}</div>
      
      </div>
      <Toaster position="top-center"/>
      </body>
      </html>
      </ClerkProvider>
    
  );
}
